package com.baidu.openrasp.woodpecker;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_header.proto

public final class RequestHeader {
  private RequestHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pb_headerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * pb版本号
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     * pb版本号
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 密钥序号
     * </pre>
     *
     * <code>required uint32 encrypt_code = 2;</code>
     */
    boolean hasEncryptCode();
    /**
     * <pre>
     * 密钥序号
     * </pre>
     *
     * <code>required uint32 encrypt_code = 2;</code>
     */
    int getEncryptCode();

    /**
     * <pre>
     * 压缩方法，0表示不压缩
     * </pre>
     *
     * <code>required uint32 compress_method = 3;</code>
     */
    boolean hasCompressMethod();
    /**
     * <pre>
     * 压缩方法，0表示不压缩
     * </pre>
     *
     * <code>required uint32 compress_method = 3;</code>
     */
    int getCompressMethod();

    /**
     * <pre>
     * 加密数据
     * </pre>
     *
     * <code>required bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <pre>
     * 加密数据
     * </pre>
     *
     * <code>required bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * 需要压缩加密 先压缩后加密
   * 所有消息头部
   * </pre>
   *
   * Protobuf type {@code pb_header}
   */
  public  static final class pb_header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb_header)
      pb_headerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use pb_header.newBuilder() to construct.
    private pb_header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pb_header() {
      version_ = 0;
      encryptCode_ = 0;
      compressMethod_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pb_header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              encryptCode_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              compressMethod_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestHeader.internal_static_pb_header_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestHeader.internal_static_pb_header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestHeader.pb_header.class, RequestHeader.pb_header.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     * pb版本号
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * pb版本号
     * </pre>
     *
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ENCRYPT_CODE_FIELD_NUMBER = 2;
    private int encryptCode_;
    /**
     * <pre>
     * 密钥序号
     * </pre>
     *
     * <code>required uint32 encrypt_code = 2;</code>
     */
    public boolean hasEncryptCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 密钥序号
     * </pre>
     *
     * <code>required uint32 encrypt_code = 2;</code>
     */
    public int getEncryptCode() {
      return encryptCode_;
    }

    public static final int COMPRESS_METHOD_FIELD_NUMBER = 3;
    private int compressMethod_;
    /**
     * <pre>
     * 压缩方法，0表示不压缩
     * </pre>
     *
     * <code>required uint32 compress_method = 3;</code>
     */
    public boolean hasCompressMethod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 压缩方法，0表示不压缩
     * </pre>
     *
     * <code>required uint32 compress_method = 3;</code>
     */
    public int getCompressMethod() {
      return compressMethod_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * 加密数据
     * </pre>
     *
     * <code>required bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 加密数据
     * </pre>
     *
     * <code>required bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompressMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, encryptCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, compressMethod_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, encryptCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, compressMethod_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestHeader.pb_header)) {
        return super.equals(obj);
      }
      RequestHeader.pb_header other = (RequestHeader.pb_header) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasEncryptCode() == other.hasEncryptCode());
      if (hasEncryptCode()) {
        result = result && (getEncryptCode()
            == other.getEncryptCode());
      }
      result = result && (hasCompressMethod() == other.hasCompressMethod());
      if (hasCompressMethod()) {
        result = result && (getCompressMethod()
            == other.getCompressMethod());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasEncryptCode()) {
        hash = (37 * hash) + ENCRYPT_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptCode();
      }
      if (hasCompressMethod()) {
        hash = (37 * hash) + COMPRESS_METHOD_FIELD_NUMBER;
        hash = (53 * hash) + getCompressMethod();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestHeader.pb_header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestHeader.pb_header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestHeader.pb_header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestHeader.pb_header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestHeader.pb_header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestHeader.pb_header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestHeader.pb_header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestHeader.pb_header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestHeader.pb_header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestHeader.pb_header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestHeader.pb_header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestHeader.pb_header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestHeader.pb_header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 需要压缩加密 先压缩后加密
     * 所有消息头部
     * </pre>
     *
     * Protobuf type {@code pb_header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_header)
        RequestHeader.pb_headerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestHeader.internal_static_pb_header_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestHeader.internal_static_pb_header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestHeader.pb_header.class, RequestHeader.pb_header.Builder.class);
      }

      // Construct using RequestHeader.pb_header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        compressMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestHeader.internal_static_pb_header_descriptor;
      }

      public RequestHeader.pb_header getDefaultInstanceForType() {
        return RequestHeader.pb_header.getDefaultInstance();
      }

      public RequestHeader.pb_header build() {
        RequestHeader.pb_header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestHeader.pb_header buildPartial() {
        RequestHeader.pb_header result = new RequestHeader.pb_header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.encryptCode_ = encryptCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.compressMethod_ = compressMethod_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestHeader.pb_header) {
          return mergeFrom((RequestHeader.pb_header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestHeader.pb_header other) {
        if (other == RequestHeader.pb_header.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasEncryptCode()) {
          setEncryptCode(other.getEncryptCode());
        }
        if (other.hasCompressMethod()) {
          setCompressMethod(other.getCompressMethod());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasEncryptCode()) {
          return false;
        }
        if (!hasCompressMethod()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestHeader.pb_header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestHeader.pb_header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       * pb版本号
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * pb版本号
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * pb版本号
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * pb版本号
       * </pre>
       *
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private int encryptCode_ ;
      /**
       * <pre>
       * 密钥序号
       * </pre>
       *
       * <code>required uint32 encrypt_code = 2;</code>
       */
      public boolean hasEncryptCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 密钥序号
       * </pre>
       *
       * <code>required uint32 encrypt_code = 2;</code>
       */
      public int getEncryptCode() {
        return encryptCode_;
      }
      /**
       * <pre>
       * 密钥序号
       * </pre>
       *
       * <code>required uint32 encrypt_code = 2;</code>
       */
      public Builder setEncryptCode(int value) {
        bitField0_ |= 0x00000002;
        encryptCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密钥序号
       * </pre>
       *
       * <code>required uint32 encrypt_code = 2;</code>
       */
      public Builder clearEncryptCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptCode_ = 0;
        onChanged();
        return this;
      }

      private int compressMethod_ ;
      /**
       * <pre>
       * 压缩方法，0表示不压缩
       * </pre>
       *
       * <code>required uint32 compress_method = 3;</code>
       */
      public boolean hasCompressMethod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 压缩方法，0表示不压缩
       * </pre>
       *
       * <code>required uint32 compress_method = 3;</code>
       */
      public int getCompressMethod() {
        return compressMethod_;
      }
      /**
       * <pre>
       * 压缩方法，0表示不压缩
       * </pre>
       *
       * <code>required uint32 compress_method = 3;</code>
       */
      public Builder setCompressMethod(int value) {
        bitField0_ |= 0x00000004;
        compressMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 压缩方法，0表示不压缩
       * </pre>
       *
       * <code>required uint32 compress_method = 3;</code>
       */
      public Builder clearCompressMethod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compressMethod_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 加密数据
       * </pre>
       *
       * <code>required bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 加密数据
       * </pre>
       *
       * <code>required bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * 加密数据
       * </pre>
       *
       * <code>required bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 加密数据
       * </pre>
       *
       * <code>required bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb_header)
    }

    // @@protoc_insertion_point(class_scope:pb_header)
    private static final RequestHeader.pb_header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestHeader.pb_header();
    }

    public static RequestHeader.pb_header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<pb_header>
        PARSER = new com.google.protobuf.AbstractParser<pb_header>() {
      public pb_header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new pb_header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pb_header> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<pb_header> getParserForType() {
      return PARSER;
    }

    public RequestHeader.pb_header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_header_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024request_header.proto\"Y\n\tpb_header\022\017\n\007v" +
      "ersion\030\001 \002(\r\022\024\n\014encrypt_code\030\002 \002(\r\022\027\n\017co" +
      "mpress_method\030\003 \002(\r\022\014\n\004data\030\004 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_header_descriptor,
        new String[] { "Version", "EncryptCode", "CompressMethod", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
