sudo: required
language: java
cache:
  yarn: true
  directories:
    - $HOME/.m2
services:
  - mysql
  - postgresql
matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
      env: SERVER=tomcat6
    - jdk: openjdk7
      env: SERVER=tomcat7
    - jdk: openjdk7
      env: SERVER=jboss4
    - jdk: openjdk7
      env: SERVER=jboss5
    - jdk: openjdk7
      env: SERVER=jboss6
    - jdk: openjdk8
      env: SERVER=tomcat8
    - jdk: openjdk8
      env: SERVER=jetty9
    - jdk: oraclejdk8
      env: SERVER=tomcat8
    - jdk: oraclejdk8
      env: SERVER=jetty9
before_install:
  - pushd integration-test
  - pushd tester && yarn && popd
  - . build-war.sh
install:
  - . build-rasp.sh
  - . start-${SERVER}.sh
  - pushd tester
script:
  - travis_retry node_modules/.bin/mocha *.test.js -t 30000 --retries 3
before_cache:
  - rm -rf $HOME/.m2/repository/com/fuxi